databases:
  - name: madeireira_ideal
    databaseName: madeireira_ideal
    user: madeireira_ideal
    plan: free

services:
  - type: web
    plan: free
    name: madeireira_ideal
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: madeireira_ideal
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false