databases:
  - name: madeirira_ideal
    databaseName: madeirira_ideal
    user: madeirira_ideal
    plan: free

services:
  - type: web
    name: madeirira_ideal
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: madeireira_ideal
          property: connectionString
