
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: madeireira_ideal_development

  
  username: madeireira_ideal

  # The password associated with the postgres role (username).
  password: madeireira_ideal


test:
  <<: *default
  database: madeireira_ideal_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: madeireira_ideal_production
  username: madeireira_ideal
  password: <%= ENV["MADEIREIRA_IDEAL_DATABASE_PASSWORD"] %>
